### ISSUE TITLE
REQUEST: Simplify connection information

### ISSUE THREAD

**Issue by vhgarandil** [neilalexander/vyatta-cjdns#7]
"show interfaces cjdns connection-details"

Would be very handy to have on the system.

**Comment by neilalexander** [comment]
Added `show interfaces cjdns <tunX> connection-details <username>` to [v0.2.6](https://github.com/neilalexander/vyatta-cjdns/tree/v0.2.6).

Release here: https://github.com/neilalexander/vyatta-cjdns/releases/tag/v0.2.6
