### ISSUE TITLE
vyos 1.2.x 

### ISSUE THREAD

**Issue by jonaswre** [neilalexander/vyatta-cjdns#8]
Hi,
I was wondering if 1.2.x is supported. If not what would have to be done to support it?

Greetings Jonas

**Comment by neilalexander** [comment]
Unless there's been a big change in how VyOS 1.2 handles template files, I think it might just work as it currently is!

If you have the means to compile and test, I'd appreciate that. Otherwise let me know and I can build some packages for you to try.

**Comment by jonaswre** [comment]
Thanks for the response, I haven't done any vyos packages so far. But from what i've read in the documentation it can't be to hard to compile right? I would setup a vyos 1.2 VM und run the .\build-vyos script within it.
